### ISSUE TITLE
Lineplot incorrectly attempts sort my already sorted data

### ISSUE THREAD

**Issue by Allong12** [mwaskom/seaborn#1645]
Whenever I try to `lineplot` my DataFrame, seaborn decides by default that it gets to decide that it isn't sorted, plotting my data from left to right instead of start to finish, the way it is indexed, leading to [weird zig zags](https://i.stack.imgur.com/ifZvM.png) in [otherwise smooth data](https://i.imgur.com/J5tpazI.png).

Why is `sort=True` enabled by default? DataFrames are indexed by very design, trying to guess what I'm using as my index defeats the purpose of even indexing my DataFrame

**Comment by mwaskom** [comment]
Because it's a plot of y as a function of x. The option not to sort is there if you want to use it.

**Comment by Allong12** [comment]
Could you explain what you mean by Y as a function of X? That would imply Y being dependent, the documentation [depicts an example](https://seaborn.pydata.org/_images/seaborn-lineplot-17.png) of what I'm trying to do as a sequential list of independent co-ordinates

```
x, y = np.random.randn(2, 5000).cumsum(axis=1)
ax = sns.lineplot(x=x, y=y, sort=False, lw=1)
```

**Comment by mwaskom** [comment]
Yes; as you note, the documentation shows you how to accomplish what you want.

**Comment by Allong12** [comment]
Alright so as I understand it, you're saying the co-ordinates can also be independent.

I should then be able to introduce a third variable dependent on the previous two:

```
x, y, z = np.random.randn(3, 5000).cumsum(axis=1)
ax = sns.lineplot(x=x, y=y, hue=z, sort=False, lw=1)
```

Is this valid code? Because running it takes a while and the [output isn't what I expected](https://i.imgur.com/2eCISjp.png), though the legend scales properly

**Comment by ashleymaeconard** [comment]
sort=False should fix the issue @Allong12!

**Comment by ArpitArtworks** [comment]
This issue still exists. Tried sort=False but the lineplot is still zig zag. Any solution around this?

**Comment by zoe1337** [comment]
I'm facing the same issue. `sort=False` has no effect, using `Seaborn 0.12.0`

**Comment by anyahess** [comment]
I'm having this problem with Seaborn 0.13.2. Big problem!
