### ISSUE TITLE
lmplot legend_out=True not working

### ISSUE THREAD

**Issue by dansind** [mwaskom/seaborn#224]
Using v 0.3.1 installed via pip, running in ipython notebook, when I run lmplot, the legend is always in the middle of the plot.

Even using the example:

```
tips = sns.load_dataset('tips')
sns.lmplot('total_bill', 'tip', tips, hue='smoker', fit_reg=False)
```

The legend lies within the borders of the plot. If I manually set  `legend_out=True`, it still doesn't affect the results.
![legend_out1](https://cloud.githubusercontent.com/assets/1246466/3377903/49d42baa-fbe4-11e3-9104-078187b9931a.png)

**Comment by blubbi321** [comment]
Having the same issue, matplotlib==2.0.0, seaborn==0.7.1

**Comment by tkf** [comment]
@blubbi321 It probably is fixed by my PR #1236.

**Comment by Banyc** [comment]
When `plt.tight_layout()` enabled, the problem still exists.
