### ISSUE TITLE
[Feature] Multiple rugplots on same plot

### ISSUE THREAD

**Issue by jeskowagner** [mwaskom/seaborn#2788]
Hi there, 

Is there a way to add multiple rugplots to the same figure? This would be useful when having unique values on one axis and multiple grouping variables to color by. I understand this is achievable with shapes/colors for groups of low cardinality but I believe can quickly get confusing. Currently, when calling `rugplot` twice the second `rugplot` draws over the first one.

Example:
```{python}
import string
import random
import numpy as np
import pandas as pd
import seaborn as sns

N = 20
groups_a = random.choices(string.ascii_letters[0:5], k=N)
groups_b = random.choices(string.ascii_uppercase[0:5], k=N)
Y = np.random.random(N)
X = range(N)
df = pd.DataFrame.from_dict({"X":X, "Y":Y, "A":groups_a,"B":groups_b})

sns.scatterplot(data=df, x="X", y="Y")
sns.rugplot(data=df, x="X", hue="A", linewidth=12)
sns.rugplot(data=df, x="X", hue="B", linewidth=12)
```

This yields:
![image](https://user-images.githubusercontent.com/35219306/166219583-2f49e0fb-8ad6-402b-a59c-0941fc82fe66.png)

Expected output would be something like:
![image](https://user-images.githubusercontent.com/35219306/166219606-ee33c480-9633-44d3-8c56-f359d1592867.png)

(of course with more modifications of cmaps etc. to make the plot more clear)

**Comment by mwaskom** [comment]
Can you be more clear about what you are asking for? If you call `rugplot` multiple times, you will get multiple rugplots on the same plot. So what is the problem?

**Comment by jeskowagner** [comment]
Hi, thanks for the quick reply. The problem is that I do not get multiple `rugplot`s, but instead the second `rugplot` draws over the first. Same goes for the second legend (see the first picture, where only one rug is visible, despite two calls to `rugplot`).
My question is how I can nudge things so that both rugs (and legends) will be shown separately.
Hope that is more clear, sorry about any confusion caused.

**Comment by mwaskom** [comment]
`rugplot` has a `height` parameter ... maybe that is what you are looking for?

**Comment by mwaskom** [comment]
How did you make the "expected output" plot? Your code has a typo so it doesn't run.

**Comment by jeskowagner** [comment]
Appreciate your help! 

I just fixed the typo for the actual result, but the "expected output" was a quick mashup in Gimp.

Regarding the height parameter:
Playing around with the heights allows me to make something that's going in the right direction, but ideally one would have some sort of spacing in between the two rugs:

![image](https://user-images.githubusercontent.com/35219306/166223531-72643fc8-7e21-4206-bff1-26eafaf7bd24.png)

**Comment by jeskowagner** [comment]
Perhaps I am being still too unclear about what I am really looking for in the bigger picture:
I am looking for a way to plot a discrete X over a continuous Y, where each X has some underlying groups that I wish to visualize separately from the data. An imaginary application could be: Patients on the X axis (discrete), age on y axis (continous), and in the rugplot some additional data, e.g. smoker status and relationship status.

**Comment by mwaskom** [comment]
> ideally one would have some sort of spacing in between the two rugs

I think you're asking for too much from a rug plot here, which is meant to show the marginal distribution of observations, and not additional categorical information. I'm still not exactly sure what you're hoping for, but I think the answer is going to require a bespoke plot with a fair amount of customization. At this point, I'd suggest defining a clear problem statement and asking on StackOverflow, since the original feature request

> Is there a way to add multiple rugplots to the same figure?

is already satisfied with existing functionality.

**Comment by jeskowagner** [comment]
Yes I understand that this might be misusing rug plots a bit much. I will think about alternative angles to this problem then. Thanks for your help!
