### ISSUE TITLE
lineplot raises an "Got both 'c' and 'color'" error when using "c" only 

### ISSUE THREAD

**Issue by ap-Codkelden** [mwaskom/seaborn#2920]
When I try to build a Lineplot with custom line color by using `c` parameter of the `sns.lineplot` function, I got TypeError:

    Got both 'c' and 'color', which are aliases of one another

although I didn't use both  'c' and 'color'.

If line color specified with `color` parameter, the code works as desired. Minimal example for reproduce:

```
import seaborn as sns
from matplotlib import pyplot as plt

ax = plt.subplot(1, 1, 1)
sns.lineplot(
    x=['a', 'c'], y=[4, 8],
    c="r",
    ax=ax)
```

Libraries versions are:

```
matplotlib==3.5.2
seaborn==0.11.2
```

Python version: 3.10.5.

**Comment by ap-Codkelden** [comment]
Edit title.

**Comment by mwaskom** [comment]
Thanks for the reproducible example. I am able to make the plot as expected on the development version, so I'm guessing this got fixed at some point (not sure exactly when).

**Comment by ap-Codkelden** [comment]
Thank you for clarification!
Since this bug isn't so critical and way to specify color via `color` still exists, I'll just await for a new release. But it may confuse some newbies 🤷🏻‍♀️
