### ISSUE TITLE
seaborn/_oldcore.py generating Futurewarning for deprecated pandas `is_categorical_dtype` and `use_inf_as_na` usage

### ISSUE THREAD

**Issue by glenn-jocher** [mwaskom/seaborn#3462]
This is more informational than a true "issue" as everything appears to be working.

I installed Ultralytics 8.0.170  in a new `venv` and at the start of training, received numerous `FutureWarnings` when `trainer` started plotting labels. Screenshot shows sample of output (continues for several more lines).

![Screenshot from 2023-09-04 17-14-33_051458.png](https://github.com/ultralytics/ultralytics/assets/62214284/4cf47b9d-2324-4579-88f4-aba3f148a82d)

## The features being warned about are:

- `pd.api.types.is_categorical_dtype`
- `pd.option_context('mode.use_inf_as_na')`

both appear to be from the `seaborn` library.

Originally referenced in https://github.com/ultralytics/ultralytics/issues/4729

**Comment by mwaskom** [comment]
Thanks, these are addressed on master already.

**Comment by paulrougieux** [comment]
I installed searborn version 0.12.2 with pip and still see these warnings when using a relplot. 

> "FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version."

There are a lot of warnings, as you can see in the OP's screenshot above. Maybe because I use facet plots, the great number of repeated warnings is quite disturbing in a notebook. I suppress them with 
```
warnings.filterwarnings("ignore", "is_categorical_dtype")
warnings.filterwarnings("ignore", "use_inf_as_na")
```

@mwaskom  is the fix on master already  inside 0.12.2 or will it come in a future release?

**Comment by paulrougieux** [comment]
Installing the latest version from the git repository with:

> pip install --force-reinstall https://github.com/mwaskom/seaborn/archive/refs/heads/master.tar.gz

Fixes the warning issues. Just need to wait for the next release on pypi.

**Comment by mwaskom** [comment]
v0.13.0 has been released with these updates.
