### ISSUE TITLE
Heatmap only has annotation text in the top row only

### ISSUE THREAD

**Issue by pybokeh** [mwaskom/seaborn#3478]
Example to duplicate the problem:

```
# Required libraries 
import seaborn as sns
import matplotlib.pyplot as plt

# Load the iris dataset into a Pandas dataframe
iris_data = sns.load_dataset('iris')

# Creating the correlation matrix of the iris dataset
iris_corr_matrix = iris_data.corr(numeric_only=True)
print(iris_corr_matrix)

# Create the heatmap using the `heatmap` function of Seaborn
sns.heatmap(iris_corr_matrix, cmap='coolwarm', annot=True)

# Display the heatmap using the `show` method of the `pyplot` module from matplotlib.
plt.show()
```

My environment:
Python 3.11.4 virtual environment via venv module, everything installed with pip
OS: Ubuntu 22.04
Seaborn version: 0.12.2
Pandas version: 2.1.0
MATPLOTLIB version: 3.8.0

My pip list output:
Package            Version
------------------ ------------
asttokens          2.4.0
atpublic           4.0
backcall           0.2.0
bidict             0.22.1
certifi            2023.7.22
charset-normalizer 3.2.0
comm               0.1.4
contourpy          1.1.1
cycler             0.11.0
debugpy            1.8.0
decorator          5.1.1
duckdb             0.8.1
duckdb-engine      0.9.2
executing          1.2.0
filelock           3.12.4
fonttools          4.42.1
greenlet           2.0.2
ibis-framework     6.2.0
idna               3.4
ipykernel          6.25.2
ipython            8.15.0
jedi               0.19.0
jupyter_client     8.3.1
jupyter_core       5.3.1
kiwisolver         1.4.5
markdown-it-py     3.0.0
matplotlib         3.8.0
matplotlib-inline  0.1.6
mdurl              0.1.2
multipledispatch   1.0.0
nest-asyncio       1.5.7
numpy              1.26.0
packaging          23.1
pandas             2.1.0
parso              0.8.3
parsy              2.1
patsy              0.5.3
pexpect            4.8.0
pickleshare        0.7.5
Pillow             10.0.1
pip                23.2.1
platformdirs       3.10.0
pooch              1.7.0
prompt-toolkit     3.0.39
psutil             5.9.5
ptyprocess         0.7.0
pure-eval          0.2.2
pyarrow            12.0.1
Pygments           2.16.1
pyparsing          3.1.1
python-dateutil    2.8.2
pytz               2023.3.post1
pyzmq              25.1.1
requests           2.31.0
rich               13.5.2
scipy              1.11.2
seaborn            0.12.2
setuptools         65.5.0
six                1.16.0
SQLAlchemy         2.0.20
sqlalchemy-views   0.3.2
sqlglot            17.16.2
stack-data         0.6.2
statsmodels        0.14.0
toolz              0.12.0
tornado            6.3.3
tqdm               4.66.1
traitlets          5.10.0
typing_extensions  4.7.1
tzdata             2023.3
urllib3            2.0.4
wcwidth            0.2.6
xxhash             3.3.0

**Comment by pybokeh** [comment]
Looks like problem goes away if I downgrade MATPLOTLIB to version 3.7.3.

**Comment by mwaskom** [comment]
Hm, I cannot replicate

<img width="472" alt="image" src="https://github.com/mwaskom/seaborn/assets/315810/3a44dc93-5e2b-4c8c-aa13-123a460294a7">

So maybe this has been already addressed on master, although nothing immediately comes to mind.

**Comment by stefanistrate** [comment]
I am having the same issue with seaborn 0.12.2 from PyPI, but things seem to be work just fine with the github master branch. Maybe it's worth pushing a new version to PyPI soon?

![Screenshot 2023-09-18 at 09 10 44](https://github.com/mwaskom/seaborn/assets/3457859/1bd11b84-117a-4479-9a96-37e54006f456)
![Screenshot 2023-09-18 at 09 13 42](https://github.com/mwaskom/seaborn/assets/3457859/907a158c-5868-474c-8748-a7d3dac1ef9c)
![Screenshot 2023-09-18 at 09 18 19](https://github.com/mwaskom/seaborn/assets/3457859/fe1b1c02-1fda-49f2-a049-78d32a018847)

**Comment by mwaskom** [comment]
It would be helpful for someone to track down the root cause here and determine if it needs to be reported upstream to matplotlib as a regression, independent of whether seaborn already has a workaround for it on the dev branch.

**Comment by thuiop** [comment]
I'll try to take a look.

**Comment by thuiop** [comment]
So the issue is that the value returned by pcolormesh is now a different class, as mentioned [here](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.8.0.html#the-object-returned-by-pcolor-has-changed-to-a-polyquadmesh-class). The `get_array` method no longer returns a flattened array by default.
This has been fixed by @ksunden in this commit https://github.com/mwaskom/seaborn/commit/b3e6b8d62194577deabebaa595520a13d55cf269.

**Comment by ylevental** [comment]
> Looks like problem goes away if I downgrade MATPLOTLIB to version 3.7.3.

Downgrading worked for me too.  It seems that this problem will be fixed soon in the pip release.

**Comment by mwaskom** [comment]
Closing this as the issue is resolved in seaborn v0.13.0 which will be released in the next day or two barring any last-minute surprises about the RC.

**Comment by engnadeau** [comment]
still reproducing the error on my end...

```
matplotlib                3.8.0
seaborn                   0.13.0
```

toy example:

```
# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets

# Load the diabetes dataset
diabetes = datasets.load_diabetes()
data = pd.DataFrame(data=diabetes.data, columns=diabetes.feature_names)
data["target"] = diabetes.target

# Correlation matrix
plt.figure(figsize=(10, 8))
sns.heatmap(data.corr(), annot=True)
plt.show()
```
	
![image](https://github.com/mwaskom/seaborn/assets/6395915/e57b1c91-6322-4683-8f8b-72585999bb82)

**Comment by mwaskom** [comment]
I am guessing you updated seaborn in a different environment, or perhaps forgot to restart your kernel:
<img width="594" alt="image" src="https://github.com/mwaskom/seaborn/assets/315810/38d0962b-9847-4a18-9835-855b0fc72845">

**Comment by engnadeau** [comment]
> I am guessing you updated seaborn in a different environment, or perhaps forgot to restart your kernel: <img alt="image" width="594" src="https://user-images.githubusercontent.com/315810/271711253-38d0962b-9847-4a18-9835-855b0fc72845.png">

yeah, caught my error but you were too fast 🤣

**Comment by rv-12** [comment]
> Looks like problem goes away if I downgrade MATPLOTLIB to version 3.7.3.

worked for me

**Comment by paulinavita** [comment]
Hi, I wonder why it's not working for me, I downgraded the matplotlib and update seaborn to latest already. Also restarted my kernel 

![image](https://github.com/mwaskom/seaborn/assets/45759716/69feb10c-2e4e-45c3-a175-e67d90405048)

I still only got the first row of the heatmap showing
![image](https://github.com/mwaskom/seaborn/assets/45759716/d3306d64-45ec-4f5f-9bb6-6212352ecdda)

Any step I am missing? Thank you

**Comment by mwaskom** [comment]
I would confirm that you actually have those versions imported in the python process where you’re making the plot

**Comment by paulinavita** [comment]
Ah, sorry about that. Yes, I confirm it works now. Thank you
