### ISSUE TITLE
Random behaviour of linewidth for violinplot and stripplot

### ISSUE THREAD

**Issue by mpschr** [mwaskom/seaborn#678]
Hi

I have a plot which randomly decides to plot the linewidth as indicated or just leave out plotting the line. Sometimes only the violinplot has border(lines), sometimes the points have the borderline exclusively and most of the time none have it. 

Here is the code - did I write someting awefully weird?

```
    plt.clf()
    fig = plt.figure(figsize=(13, 6.5))
    fig, (ax1) = plt.subplots(1, 1, sharey=True, figsize=(13, 6.5))
    sns.set_palette('pastel')
    sns.violinplot(x='sample', y='alt_freq', data=varfreq_df, hue='mutations', edgecolor='grey',
                        linewidth=1, ax=ax1)
    sns.stripplot(y="alt_freq", x="sample", data=varfreq_df, hue='mutations', linewidth=1, ax=ax1,
                       jitter=1, color='white', edgecolor='grey', alpha=.4, size=4)
    plt.savefig(os.path.join(reporter.out_folder, '~/Desktop/violins.png'))
```

Here below three products of teh same code.

![violins_sub](https://cloud.githubusercontent.com/assets/1090105/9331120/de5b71a6-45bd-11e5-8bcb-f3702a2d6468.png)

**Comment by mwaskom** [comment]
I changed your script to use the tips dataset and couldn't reproduce the behavior. It would be useful to have more information, like software versions, matplotlib backend, etc.

**Comment by mpschr** [comment]
Sorry, of course:
Python 3.4.3 |Anaconda 2.2.0 (64-bit)| (default, Jun  4 2015, 15:29:08) 
seaborn 0.6.0
matplotlib 1.4.3

Could you post the adapted script, so I can see if on my machine I can reproduce with other data?

**Comment by mwaskom** [comment]
I think it might be related to https://github.com/mwaskom/seaborn/issues/519, which is ultimately a matplotlib bug on python 3. Do you have a Python 2 install you could try it on?

**Comment by mpschr** [comment]
Sorry - no, I did not manage to produce the same plots on python2

**Comment by mwaskom** [comment]
OK I think this is a bug in matplotlib on Python 3 that has been fixed in the development version. Going to close as there's nothing for seaborn to do.

**Comment by tritemio** [comment]
@mwaskom do you have a reference for the matplotlib bug? I still have this intermittent problem with violinplot under python 3.4 and matplotlib 1.5 (Windows x64).

I can reproduce it with (on repeated runs sometimes the plot has not edges):

```
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

a = [np.random.randn(10), np.random.randn(7)]
sns.violinplot(data=a, inner='sticks')
```

**Comment by tritemio** [comment]
Confirmed matplotlib bug, as a temporary workaround I call `patch_violinplot()` to fix the problem:

```
def patch_violinplot():
    """Patch seaborn's violinplot in current axis to workaround matplotlib's bug ##5423."""
    from matplotlib.collections import PolyCollection
    ax = plt.gca()
    for art in ax.get_children():
        if isinstance(art, PolyCollection):
            art.set_edgecolor((0.3, 0.3, 0.3))
```

But it looks like seaborn can also avoid the issue using `facecolor` instead of `color` in (which is apparently a more "robust" keyword):

https://github.com/mwaskom/seaborn/blob/master/seaborn/categorical.py#L798

**Comment by mwaskom** [comment]
Thanks for following up on this. It should be easy to change the parameter
seaborn uses for better compatability. Can you open a new issue about it so
that it is easier to track? Thanks
